### ISSUE TITLE
Error in 'build' while "Parsing gtf": FileFormatException

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/cellbase#144]
trying to build d.rerio release-81, using the master branch (commit 8f0b779), got this error while trying to parse [the gtf file](ftp://ftp.ensembl.org/pub/release-81/gtf/danio_rerio/Danio_rerio.GRCz10.81.gtf.gz):

```java
[main] INFO org.opencb.cellbase.app.transform.GeneParser - Parsing gtf...
[main] ERROR class org.opencb.cellbase.app.cli.BuildCommandExecutor - Error executing 'build' command all: java.lang.ArrayIndexOutOfBoundsException: 8
org.opencb.biodata.formats.io.FileFormatException: java.lang.ArrayIndexOutOfBoundsException: 8
	at org.opencb.biodata.formats.feature.gtf.io.GtfReader.read(GtfReader.java:61)
	at org.opencb.cellbase.app.transform.GeneParser.parse(GeneParser.java:118)
	at org.opencb.cellbase.app.cli.BuildCommandExecutor.execute(BuildCommandExecutor.java:168)
	at org.opencb.cellbase.app.CellBaseMain.main(CellBaseMain.java:95)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8
	at org.opencb.biodata.formats.feature.gtf.io.GtfReader.read(GtfReader.java:38)
	... 3 more
```

the offending line is actually GtfReader.java:42:
```java
40:                String[] fields = e.split("\t");
41:                HashMap attributes = new HashMap();
42:                String[] attrFields = fields[8].split(";");
```
where e is a string "4	ensembl	transcript	6961	9663	.	-	.	", so fields.length is 8 (0 to 7), and fields[8] throws AIOFBE. 

Turns out, the file format was changed, 
ftp://ftp.ensembl.org/pub/release-81/gtf/danio_rerio/Danio_rerio.GRCz10.81.gtf.gz, ftp://ftp.ensembl.org/pub/release-79/gtf/danio_rerio/Danio_rerio.Zv9.79.gtf.gz. Guess this issue should be moved to https://github.com/opencb/biodata.

**Comment by mbsimonovic** [comment]
hm, according to [the GTF file format spec](http://www.ensembl.org/info/website/upload/gff.html): _all but the final field in each feature line must contain a value; "empty" columns should be denoted with a '.'_, which means the gtf file is not valid, and seems like they fixed it as of release-83
