### ISSUE TITLE
Can't build Human genes

### ISSUE THREAD

**Issue by apaytuvi** [opencb/cellbase#302]
Hi @dunk @aaleman @mbsimonovic @mh11 @mbleda 

I do:

```
#download
../build/bin/cellbase.sh download -a GRCh38 --common ./GRCh38_common/ -d gene -o ./GRCh38/ -s hsapiens

#build data
../build/bin/cellbase.sh build --input ./GRCh38/homo_sapiens_grch38/ --common ./GRCh38_common/ --output ./GRCh38_build/ --data gene
```
Genome is build perfectly, but genes no. The first error I'm having is the following:
```
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.opencb.biodata.formats.io.BeanReader.getFirstLineUncommented(BeanReader.java:194)
	at org.opencb.biodata.formats.io.BeanReader.createConstructor(BeanReader.java:62)
	at org.opencb.biodata.formats.io.BeanReader.<init>(BeanReader.java:57)
	at org.opencb.biodata.formats.io.BeanReader.<init>(BeanReader.java:49)
	at org.opencb.biodata.formats.feature.gff.io.Gff2Reader.<init>(Gff2Reader.java:39)
	at org.opencb.cellbase.app.transform.GeneParserUtils.getTfbsMap(GeneParserUtils.java:50)
	at org.opencb.cellbase.app.transform.GeneParser.parse(GeneParser.java:122)
	at org.opencb.cellbase.app.cli.BuildCommandExecutor.execute(BuildCommandExecutor.java:183)
	at org.opencb.cellbase.app.CellBaseMain.main(CellBaseMain.java:91)
```

If I remove `MotifFeatures.gff.gz` this specific error disappears.

Then, I try the build again and:

```
Empty block, this should be redesigned
Empty block, this should be redesigned
Empty block, this should be redesigned
Empty block, this should be redesigned
Empty block, this should be redesigned
Empty block, this should be redesigned
Empty block, this should be redesigned
Empty block, this should be redesigned
[main] ERROR class org.opencb.cellbase.app.cli.BuildCommandExecutor - Error executing 'build' command gene: null
java.lang.NullPointerException
	at java.lang.String.<init>(String.java:566)
	at org.opencb.biodata.tools.sequence.fasta.FastaIndexManager.query(FastaIndexManager.java:165)
	at org.opencb.cellbase.app.transform.GeneParser.parse(GeneParser.java:220)
	at org.opencb.cellbase.app.cli.BuildCommandExecutor.execute(BuildCommandExecutor.java:183)
	at org.opencb.cellbase.app.CellBaseMain.main(CellBaseMain.java:91)
```

For your information:

```
cat GRCh38/homo_sapiens_grch38/gene/ensemblCoreVersion.json 
{"downloadDate":"20161129_160601","uRL":["ftp://ftp.ensembl.org/pub/release-82/gtf/homo_sapiens/*82.gtf.gz","ftp://ftp.ensembl.org/pub/release-82/fasta/homo_sapiens/pep/*.pep.all.fa.gz","ftp://ftp.ensembl.org/pub/release-82/fasta/homo_sapiens/cdna/*.cdna.all.fa.gz","ftp://ftp.ensembl.org/pub/release-82/regulation/homo_sapiens/MotifFeatures.gff.gz"],"data":"gene","source":"ENSEMBL","version":"82_38"}
```

**Comment by javild** [comment]
Hi @apaytuvi 
is there any particular reason why you would want to build the data models for GRCh38 by yourself? Downloading sources data and building the data models is often quite tricky. We've already done that work for Human GRCh38 and you can directly download the result from:
http://bioinfo.hpc.cam.ac.uk/downloads/cellbase/v4/homo_sapiens_grch38/mongodb/

**Comment by javild** [comment]
This issue has been inactive for a number of days. Closing it. May be reopened if necessary
