### ISSUE TITLE
Cellbase variant annotation fails on master branch for VEP output

### ISSUE THREAD

**Issue by cjp64** [opencb/cellbase#310]
Hi there,
Cellbase variant annotation fails on master branch for VEP output.
Chris

% ./cellbase.sh variant-annotation -a GRCh37 -s hsapiens -i ~/test.vcf.gz --output-format VEP -o ~/test.vep
2017-01-17 11:46:41 [main] INFO VariantAnnotationCommandExecutor:357 - Using HTSJDK to read variants.
2017-01-17 11:46:41 [main] INFO VariantAnnotationCommandExecutor:357 - Using HTSJDK to read variants.
2017-01-17 11:46:41 [main] INFO VariantAnnotationCommandExecutor:357 - Using HTSJDK to read variants.
2017-01-17 11:46:41 [main] INFO VariantAnnotationCommandExecutor:357 - Using HTSJDK to read variants.
2017-01-17 11:46:43 [pool-1-thread-5] ERROR ParallelTaskRunner:704 - Error writing batch 0
java.lang.NullPointerException
   at org.opencb.biodata.formats.variant.annotation.io.VepFormatWriter.write(VepFormatWriter.java:154)
   at org.opencb.biodata.formats.variant.annotation.io.VepFormatWriter.write(VepFormatWriter.java:185)
   at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:702)
   at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.call(ParallelTaskRunner.java:685)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
2017-01-17 11:46:43 [pool-1-thread-5] WARN  ParallelTaskRunner:710 - Abort writing thread on fail
2017-01-17 11:46:44 [pool-1-thread-4] WARN  ParallelTaskRunner:606 - Abort task thread on fail
2017-01-17 11:46:45 [pool-1-thread-2] WARN  ParallelTaskRunner:606 - Abort task thread on fail
2017-01-17 11:46:45 [pool-1-thread-3] WARN  ParallelTaskRunner:606 - Abort task thread on fail
2017-01-17 11:46:46 [pool-1-thread-1] WARN  ParallelTaskRunner:606 - Abort task thread on fail
java.lang.IllegalStateException: No runners but queue with 10 items!!!
   at org.opencb.commons.run.ParallelTaskRunner.readLoop(ParallelTaskRunner.java:491)
   at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:322)
   at org.opencb.commons.run.ParallelTaskRunner.run(ParallelTaskRunner.java:283)
   at org.opencb.cellbase.app.cli.VariantAnnotationCommandExecutor.runAnnotation(VariantAnnotationCommandExecutor.java:242)
   at org.opencb.cellbase.app.cli.VariantAnnotationCommandExecutor.execute(VariantAnnotationCommandExecutor.java:141)

**Comment by javild** [comment]
Fixed. Was actually an opencb/biodata bug at VepFormatWriter:
https://github.com/opencb/biodata/issues/143
