### ISSUE TITLE
load human: mongodb error Size 55197755 is larger than MaxDocumentSize 16793600

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/cellbase#331]
I'm trying to import a previous archive of 
[http://bioinfo.hpc.cam.ac.uk/downloads/cellbase/v4/homo_sapiens_grch38/mongodb/](http://bioinfo.hpc.cam.ac.uk/downloads/cellbase/v4/homo_sapiens_grch38/mongodb/), genomeVersion.json:

```json
{"downloadDate":"20161012_124412","uRL":["ftp://ftp.ensembl.org/pub/release-82/fasta/homo_sapiens/dna/*.dna.primary_assembly.fa.gz"],"data":"genome","source":"ENSEMBL","version":"82_38"}
```

and getting this error:

```
ERROR MongoDBCellBaseLoader:372 - Error Loading batch: Size 18541983 is larger than MaxDocumentSize 16793600.
...
ERROR MongoDBCellBaseLoader:372 - Error Loading batch: Size 55197755 is larger than MaxDocumentSize 16793600.
```

Stack trace: 
```shell
2017-04-10 12:50:56 [main] INFO  LoadRunner:165 - 6460000 records read from hsapiens/variation_chr9.full.json.gz
org.bson.BsonSerializationException: Size 55197755 is larger than MaxDocumentSize 16793600.
	at org.bson.BsonBinaryWriter.backpatchSize(BsonBinaryWriter.java:367)
	at org.bson.BsonBinaryWriter.doWriteEndArray(BsonBinaryWriter.java:142)
	at org.bson.AbstractBsonWriter.writeEndArray(AbstractBsonWriter.java:338)
	at org.bson.codecs.DocumentCodec.writeIterable(DocumentCodec.java:199)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:170)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:172)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:172)
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:131)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:101)
	at com.mongodb.connection.InsertCommandMessage.writeTheWrites(InsertCommandMessage.java:43)
	at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBodyWithMetadata(BaseWriteCommandMessage.java:129)
	at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160)
	at com.mongodb.connection.WriteCommandProtocol.sendMessage(WriteCommandProtocol.java:212)
	at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:101)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:67)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:37)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.insertCommand(DefaultServerConnection.java:115)
	at com.mongodb.operation.MixedBulkWriteOperation$Run$2.executeWriteCommandProtocol(MixedBulkWriteOperation.java:455)
	at com.mongodb.operation.MixedBulkWriteOperation$Run$RunExecutor.execute(MixedBulkWriteOperation.java:646)
	at com.mongodb.operation.MixedBulkWriteOperation$Run.execute(MixedBulkWriteOperation.java:401)
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:179)
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:168)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:230)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:221)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:168)
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:74)
	at com.mongodb.Mongo.execute(Mongo.java:781)
	at com.mongodb.Mongo$2.execute(Mongo.java:764)
	at com.mongodb.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:291)
	at org.opencb.commons.datastore.mongodb.MongoDBNativeQuery.insert(MongoDBNativeQuery.java:167)
	at org.opencb.commons.datastore.mongodb.MongoDBCollection.insert(MongoDBCollection.java:387)
	at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.load(MongoDBCellBaseLoader.java:527)
	at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.prepareBatchAndLoad(MongoDBCellBaseLoader.java:365)
	at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.call(MongoDBCellBaseLoader.java:316)
	at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.call(MongoDBCellBaseLoader.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-04-10 12:50:57 [pool-4-thread-1] ERROR MongoDBCellBaseLoader:372 - Error Loading batch: Size 55197755 is larger than MaxDocumentSize 16793600.
2017-04-10 12:50:57 [main] INFO  LoadRunner:165 - 6461000 records read from hsapiens/variation_chr9.full.json.gz

```

**Comment by javild** [comment]
Hi @mbsimonovic 
Thanks for reporting this issue. 
We are aware of it - we observed it in 7 variants (e82 variation) which document grows so much that does not fit into the 16MB. There is

**Comment by imedina** [comment]
If I remember correctly those 7 variants raised the error and they just were not loaded, but this error does not stop the loading process, the rest of them should be loaded.

**Comment by javild** [comment]
Closing... can re-open if needed
