### ISSUE TITLE
Add REST server option in CellBase

### ISSUE THREAD

**Issue by wbari** [opencb/cellbase#408]

**Comment by julie-sullivan** [comment]
I'm having problems with jetty. Is it because there is another jetty on the classpath?

Also I don't understand how `mortbay` can be on the classpath without being in a POM. Is it a dependency of some other library?

```
~/git/cellbase (feature-restserver) $ grep -i -r "mortbay" ./
./cellbase-lib/src/test/java/org/opencb/cellbase/lib/builders/RepeatsParserTest.java:import org.mortbay.util.ajax.JSON;
./cellbase-lib/src/test/java/org/opencb/cellbase/lib/builders/DgvParserTest.java:import org.mortbay.util.ajax.JSON;
Binary file ./cellbase-lib/target/test-classes/org/opencb/cellbase/lib/builders/DgvParserTest.class matches
Binary file ./cellbase-lib/target/test-classes/org/opencb/cellbase/lib/builders/RepeatsParserTest.class matches
./cellbase-lib/cellbase-lib.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:jetty:6.1.26" level="project" />
./cellbase-lib/cellbase-lib.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:jetty-util:6.1.26" level="project" />
./cellbase-lib/cellbase-lib.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:servlet-api:2.5-20081211" level="project" />
./.idea/libraries/Maven__org_mortbay_jetty_jetty_6_1_26.xml:  <library name="Maven: org.mortbay.jetty:jetty:6.1.26">
./.idea/libraries/Maven__org_mortbay_jetty_jetty_6_1_26.xml:      <root url="jar://$MAVEN_REPOSITORY$/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar!/" />
./.idea/libraries/Maven__org_mortbay_jetty_jetty_6_1_26.xml:      <root url="jar://$MAVEN_REPOSITORY$/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26-javadoc.jar!/" />
./.idea/libraries/Maven__org_mortbay_jetty_jetty_6_1_26.xml:      <root url="jar://$MAVEN_REPOSITORY$/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26-sources.jar!/" />
./.idea/libraries/Maven__org_mortbay_jetty_jetty_util_6_1_26.xml:  <library name="Maven: org.mortbay.jetty:jetty-util:6.1.26">
./.idea/libraries/Maven__org_mortbay_jetty_jetty_util_6_1_26.xml:      <root url="jar://$MAVEN_REPOSITORY$/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar!/" />
./.idea/libraries/Maven__org_mortbay_jetty_jetty_util_6_1_26.xml:      <root url="jar://$MAVEN_REPOSITORY$/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26-javadoc.jar!/" />
./.idea/libraries/Maven__org_mortbay_jetty_jetty_util_6_1_26.xml:      <root url="jar://$MAVEN_REPOSITORY$/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26-sources.jar!/" />
./.idea/libraries/Maven__org_mortbay_jetty_servlet_api_2_5_20081211.xml:  <library name="Maven: org.mortbay.jetty:servlet-api:2.5-20081211">
./.idea/libraries/Maven__org_mortbay_jetty_servlet_api_2_5_20081211.xml:      <root url="jar://$MAVEN_REPOSITORY$/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211.jar!/" />
./.idea/libraries/Maven__org_mortbay_jetty_servlet_api_2_5_20081211.xml:      <root url="jar://$MAVEN_REPOSITORY$/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211-javadoc.jar!/" />
./.idea/libraries/Maven__org_mortbay_jetty_servlet_api_2_5_20081211.xml:      <root url="jar://$MAVEN_REPOSITORY$/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211-sources.jar!/" />
./cellbase-client/cellbase-client.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:jetty:6.1.26" level="project" />
./cellbase-client/cellbase-client.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:jetty-util:6.1.26" level="project" />
./cellbase-client/cellbase-client.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:servlet-api:2.5-20081211" level="project" />
./cellbase-app/src/main/java/org/opencb/cellbase/app/cli/main/annotation/JsonStringAnnotatorTask.java:import org.mortbay.util.ajax.JSON;
./cellbase-app/cellbase-app.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:jetty:6.1.26" level="project" />
./cellbase-app/cellbase-app.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:jetty-util:6.1.26" level="project" />
./cellbase-app/cellbase-app.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:servlet-api:2.5-20081211" level="project" />
./cellbase-server/cellbase-server.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:jetty:6.1.26" level="project" />
./cellbase-server/cellbase-server.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:jetty-util:6.1.26" level="project" />
./cellbase-server/cellbase-server.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:servlet-api:2.5-20081211" level="project" />
Binary file ./cellbase-server/target/cellbase-server-5.0.0-SNAPSHOT/WEB-INF/lib/servlet-api-2.5-20081211.jar matches
Binary file ./cellbase-server/target/cellbase-server-5.0.0-SNAPSHOT/WEB-INF/lib/jetty-util-6.1.26.jar matches
Binary file ./cellbase-server/target/cellbase-server-5.0.0-SNAPSHOT/WEB-INF/lib/jetty-6.1.26.jar matches
Binary file ./cellbase-server/target/cellbase-server-4.8.0-SNAPSHOT/WEB-INF/lib/servlet-api-2.5-20081211.jar matches
Binary file ./cellbase-server/target/cellbase-server-4.8.0-SNAPSHOT/WEB-INF/lib/jetty-util-6.1.26.jar matches
Binary file ./cellbase-server/target/cellbase-server-4.8.0-SNAPSHOT/WEB-INF/lib/jetty-6.1.26.jar matches
./cellbase-core/cellbase-core.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:jetty:6.1.26" level="project" />
./cellbase-core/cellbase-core.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:jetty-util:6.1.26" level="project" />
./cellbase-core/cellbase-core.iml:    <orderEntry type="library" name="Maven: org.mortbay.jetty:servlet-api:2.5-20081211" level="project" />


```

**Comment by julie-sullivan** [comment]
My deps are wrong, but they look the same as opencga (to me!):

```
Caused by: java.lang.NoClassDefFoundError: org/glassfish/jersey/server/internal/inject/AbstractHttpContextValueFactory
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.getDeclaringClass0(Native Method)
        at java.lang.Class.getDeclaringClass(Class.java:1235)
        at java.lang.Class.getEnclosingClass(Class.java:1277)
        at java.lang.Class.getSimpleBinaryName(Class.java:1443)
        at java.lang.Class.isMemberClass(Class.java:1433)
        at org.glassfish.jersey.internal.inject.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:137)
        at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:178)
        at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:128)
        at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:179)
        at org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:723)
        at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:678)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:459)
        ... 43 more
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.server.internal.inject.AbstractHttpContextValueFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 67 more
```
