### ISSUE TITLE
Build: exception thrown if common is not specified

### ISSUE THREAD

**Issue by julie-sullivan** [opencb/cellbase#439]
I downloaded data, not specifying "common":

```
~/git/cellbase/build:issue-386$ ./bin/cellbase.sh download -d gene -s hsapiens
```

Then tried the build:

```
~/git/cellbase/build:issue-386$ ./bin/cellbase.sh build -d gene -s hsapiens -i /tmp
Exception in thread "main" java.lang.NullPointerException
	at org.opencb.cellbase.app.cli.BuildCommandExecutor.<init>(BuildCommandExecutor.java:81)
	at org.opencb.cellbase.app.CellBaseMain.main(CellBaseMain.java:66)
```

Which is looking for the common directory

```
        if (buildCommandOptions.common != null) {
            common = Paths.get(buildCommandOptions.common);
        } else {
            common = input.getParent().getParent().resolve("common");
        }
```

But i do have a common directory 

```
/tmp/common/expression:$ ls
allgenes_updown_in_organism_part.tab.gz		allgenes_updown_in_organism_part.tab.gz.log	geneExpressionAtlasVersion.json
```

**Comment by julie-sullivan** [comment]
It doesn't like when I specify common either.

```
~/git/cellbase/build:issue-386$ ./bin/cellbase.sh build -d gene -s hsapiens -i /tmp --common /tmp/common
2019-10-11 09:30:13 [main] INFO  BuildCommandExecutor:130 - Building 'gene' data
2019-10-11 09:30:13 [main] WARN  BuildCommandExecutor:228 - Version file /tmp/gene/geneDrug/dgidbVersion.json not found - skipping
2019-10-11 09:30:13 [main] WARN  BuildCommandExecutor:228 - Version file /tmp/gene/ensemblCoreVersion.json not found - skipping
2019-10-11 09:30:13 [main] WARN  BuildCommandExecutor:228 - Version file /tmp/gene/uniprotXrefVersion.json not found - skipping
2019-10-11 09:30:13 [main] WARN  BuildCommandExecutor:228 - Version file /tmp/gene/hpoVersion.json not found - skipping
2019-10-11 09:30:13 [main] WARN  BuildCommandExecutor:228 - Version file /tmp/gene/disgenetVersion.json not found - skipping
2019-10-11 09:30:13 [main] WARN  BuildCommandExecutor:228 - Version file /tmp/gene/gnomadVersion.json not found - skipping
java.nio.file.NoSuchFileException: /tmp/genome
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
	at java.nio.file.Files.newDirectoryStream(Files.java:589)
	at org.opencb.cellbase.app.cli.BuildCommandExecutor.getFastaReferenceGenome(BuildCommandExecutor.java:467)
	at org.opencb.cellbase.app.cli.BuildCommandExecutor.buildGene(BuildCommandExecutor.java:291)
	at org.opencb.cellbase.app.cli.BuildCommandExecutor.execute(BuildCommandExecutor.java:140)
	at org.opencb.cellbase.app.CellBaseMain.main(CellBaseMain.java:91)
Exception in thread "main" java.lang.NullPointerException
	at org.opencb.cellbase.app.transform.GeneParser.getGtfFileFromGeneDirectoryPath(GeneParser.java:938)
	at org.opencb.cellbase.app.transform.GeneParser.<init>(GeneParser.java:110)
	at org.opencb.cellbase.app.cli.BuildCommandExecutor.buildGene(BuildCommandExecutor.java:293)
	at org.opencb.cellbase.app.cli.BuildCommandExecutor.execute(BuildCommandExecutor.java:140)
	at org.opencb.cellbase.app.CellBaseMain.main(CellBaseMain.java:91)
```
