### ISSUE TITLE
Error on Load

### ISSUE THREAD

**Issue by julie-sullivan** [opencb/cellbase#489]
This is my command:

```
~/git/cellbase (issue-478) $ ./build/bin/cellbase-admin.sh load --database cellbase_hsapiens_grch38_v5 -d gene -i /tmp/homo_sapiens_grch38/generated_json/

```

Something is wrong with the 12,001st gene:
```
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 1000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 2000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 3000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz            
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 4000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz        
[pool-1-thread-1] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:79}] to localhost:27017    
[pool-1-thread-2] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:78}] to localhost:27017
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 5000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 6000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz             
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 7000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 8000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz           
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 9000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 10000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 11000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 12000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz                     
java.lang.NullPointerException                     
        at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.load(MongoDBCellBaseLoader.java:746)                                   
        at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.prepareBatchAndLoad(MongoDBCellBaseLoader.java:422)                     
        at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.call(MongoDBCellBaseLoader.java:373)
        at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.call(MongoDBCellBaseLoader.java:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                         
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                                      
        at java.lang.Thread.run(Thread.java:748)      

```

We cannot eliminate the possibility this is due to user error.

**Comment by julie-sullivan** [comment]
I'm thinking this might be related to the problem I am getting loading? Or maybe not

```
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 1000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 2000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 3000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz            
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 4000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz        
[pool-1-thread-1] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:79}] to localhost:27017    
[pool-1-thread-2] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:78}] to localhost:27017
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 5000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 6000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz             
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 7000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 8000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz           
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 9000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 10000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 11000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz
[main] INFO org.opencb.cellbase.core.loader.LoadRunner - 12000 records read from /tmp/homo_sapiens_grch38/generated_json/gene.json.gz                     
java.lang.NullPointerException                     
        at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.load(MongoDBCellBaseLoader.java:746)                                   
        at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.prepareBatchAndLoad(MongoDBCellBaseLoader.java:422)                     
        at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.call(MongoDBCellBaseLoader.java:373)
        at org.opencb.cellbase.lib.loader.MongoDBCellBaseLoader.call(MongoDBCellBaseLoader.java:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                         
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                                      
        at java.lang.Thread.run(Thread.java:748)          
```

**Comment by julie-sullivan** [comment]
The error is here: https://github.com/opencb/cellbase/blob/next/cellbase-lib/src/main/java/org/opencb/cellbase/lib/loader/MongoDBCellBaseLoader.java#L745

If I just insert the documents, no error.

**Comment by julie-sullivan** [comment]
Fixed by https://github.com/opencb/cellbase/commit/1afcf7df8ef1ca826a9b72464abb43607e8bdc7c
