### ISSUE TITLE
REST server not returning results

### ISSUE THREAD

**Issue by julie-sullivan** [opencb/cellbase#495]
Requests for gene.count and meta/status work in the tomcat, but do not return the correct results for REST. 

http://localhost:8080/cellbase/webservices/#!/Meta/status
http://localhost:8080/cellbase/webservices/#!/Gene/count

```
2019-12-05 14:10:30 [qtp1307904972-15] WARN  HttpChannel:597 - /cellbase/webservices/rest/v4/meta/hsapiens/status
javax.servlet.ServletException: A MultiException has 2 exceptions.  They are:
1. org.opencb.cellbase.server.exception.SpeciesException: Species not valid: 'null'
2. java.lang.IllegalStateException: Unable to perform operation: create on org.opencb.cellbase.server.rest.MetaWSServer
    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:408)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
    at org.opencb.cellbase.server.rest.CORSFilter.doFilter(CORSFilter.java:43)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle(Server.java:505)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:786)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:743)
    at java.lang.Thread.run(Thread.java:748)
Caused by: A MultiException has 2 exceptions.  They are:
1. org.opencb.cellbase.server.exception.SpeciesException: Species not valid: 'null'
2. java.lang.IllegalStateException: Unable to perform operation: create on org.opencb.cellbase.server.rest.MetaWSServer
    at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:368)
    at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
    at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:59)
    at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:758)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:721)
    at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:691)
    at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:160)
    at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:30)
    at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:105)
    at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:260)
    at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:51)
    at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:86)
    at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
    at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
    at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
    at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
    at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:69)
    at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:38)
    at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:245)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
    ... 37 more
Caused by: org.opencb.cellbase.server.exception.SpeciesException: Species not valid: 'null'
    at org.opencb.cellbase.server.rest.GenericRestWSServer.checkPathParams(GenericRestWSServer.java:242)
    at org.opencb.cellbase.server.rest.GenericRestWSServer.initQuery(GenericRestWSServer.java:233)
    at org.opencb.cellbase.server.rest.GenericRestWSServer.<init>(GenericRestWSServer.java:186)
    at org.opencb.cellbase.server.rest.MetaWSServer.<init>(MetaWSServer.java:67)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1356)
    at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:248)
    at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:342)
    ... 66 more
```

**Comment by julie-sullivan** [comment]
localhost:9090/cellbase-5.0.0-SNAPSHOT/webservices/#!/Species/

gets this error

```
2019-12-05 14:36:15 [qtp1115201599-13] INFO  SpeciesWSServer:286 - http://127.0.1.1:9090/cellbase-5.0.0-SNAPSHOT/webservices/rest/v4/hsapiens   {}      {"exclude":["_id","_chunkIds"]} 2       ok                                            
queryResponse.getResponses().get(0).toString() = Not valid option                                                                                                                                                                             
com.fasterxml.jackson.databind.JsonMappingException: Class java.lang.String not subtype of [simple type, class org.opencb.cellbase.core.result.CellBaseDataResult<java.lang.Object>] (through reference chain: org.opencb.cellbase.core.CellB$
seDataResponse["responses"]->java.util.ArrayList[0])                                                                                                                                                                                          
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)                                                                                                                                    
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)                                                                                                                                    
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:338)                                                                                                                                          
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:123)                                                                                                                    
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)                                                                                                                             
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)                                                                                                                             
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)                                                                                                                                
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)                                                                                                                             
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)                                                                                                                                               
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)                                                                                                                        
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)                                                                                                                    
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433)                                                                                                                                             
        at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1135)                                                                                                                                           
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1005)                                                                                                                                             
        at org.opencb.cellbase.server.rest.GenericRestWSServer.createJsonResponse(GenericRestWSServer.java:408)                                                                                                                               
        at org.opencb.cellbase.server.rest.GenericRestWSServer.createOkResponse(GenericRestWSServer.java:390)                                                                                                                                 
        at org.opencb.cellbase.server.rest.GenericRestWSServer.defaultMethod(GenericRestWSServer.java:312)  
```

**Comment by julie-sullivan** [comment]
tomcat is giving me a NULL pointer for the /status end point

```
[http-nio-8080-exec-22] INFO org.opencb.cellbase.server.rest.CellBaseExceptionMapper - http://localhost:8080/cellbase-5.0.0-SNAPSHOT/webservices/rest/v4/meta/hsapiens/status	{"limit":"-1","count":"false","skip":"-1","skipCount":"false","Output format":"json"}	error
java.lang.NullPointerException
	at org.opencb.cellbase.core.monitor.Monitor.runRemoteMonitoring(Monitor.java:95)
	at org.opencb.cellbase.core.monitor.Monitor.run(Monitor.java:90)
	at org.opencb.cellbase.server.rest.MetaWSServer.status(MetaWSServer.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by julie-sullivan** [comment]
fixed by 66efc9cf3d6b749d9a87405eb053c97c0d3ab000 and f1ba02389510d4eb9ef6e47e66859da5b77385ff

**Comment by julie-sullivan** [comment]
not fixed. the opposite of fixed.

**Comment by julie-sullivan** [comment]
user error, is fixed now.
