### ISSUE TITLE
REST error: gene Count is empty

### ISSUE THREAD

**Issue by julie-sullivan** [opencb/cellbase#498]
@wbari reports that tomcat is just fine but when he uses gene/count for rest, the results are always zero.

```
Dec 09, 2019 10:17:20 AM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 2
java.io.IOException: Path '/home/wasim/appl/cellbase/cellbase-server/../build/conf/configuration.yml' does not exist
	at org.opencb.commons.utils.FileUtils.checkPath(FileUtils.java:47)
	at org.opencb.commons.utils.FileUtils.checkFile(FileUtils.java:64)
	at org.opencb.commons.utils.FileUtils.checkFile(FileUtils.java:60)
	at org.opencb.commons.utils.FileUtils.newInputStream(FileUtils.java:115)
	at org.opencb.cellbase.core.config.CellBaseConfiguration.load(CellBaseConfiguration.java:58)
	at org.opencb.cellbase.server.rest.GenericRestWSServer.init(GenericRestWSServer.java:219)
	at org.opencb.cellbase.server.rest.GenericRestWSServer.<init>(GenericRestWSServer.java:196)
	at org.opencb.cellbase.server.rest.feature.GeneWSServer.<init>(GeneWSServer.java:63)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
-- snip --
```
this is when he compiled the code locally and deployed on another server. He also tried with the published image on docker hub and got NO error, but still got zero results. 

I can't reproduce this locally, everything works as expected.

**Comment by julie-sullivan** [comment]
Fixed. See #495 and #499
