### ISSUE TITLE
ClinVar: Load SCVs

### ISSUE THREAD

**Issue by julie-sullivan** [opencb/cellbase#518]
We load RCVs and VCVs, let's also load SCVs. Should be similar data to RCVs. I hope.

**Comment by julie-sullivan** [comment]
why is `full` required?

```
java.io.FileNotFoundException: File /mydata/json/clinical_variants.full.json.gz does not exist
	at org.opencb.cellbase.app.cli.LoadCommandExecutor.loadClinical(LoadCommandExecutor.java:319)
	at org.opencb.cellbase.app.cli.LoadCommandExecutor.execute(LoadCommandExecutor.java:160)
	at org.opencb.cellbase.app.CellBaseMain.main(CellBaseMain.java:91)
```

**Comment by julie-sullivan** [comment]
```
    public static final String CLINICAL_VARIANTS_JSON_FILE = "clinical_variants.json.gz";
    public static final String CLINICAL_VARIANTS_ANNOTATED_JSON_FILE = "clinical_variants.full.json.gz";
```

I only have the JSON file.

**Comment by julie-sullivan** [comment]
```
			{
				"source" : {
					"name" : "clinvar",
					"version" : null,
					"date" : null
				},
				"submissions" : [
					{
						"submitter" : "Tuberous sclerosis database (TSC2)",
						"date" : "20170429",
						"id" : null
					}
				],
				"somaticInformation" : null,
				"url" : "https://www.ncbi.nlm.nih.gov/clinvar/SCV000083772",
				"id" : "SCV000083772",
				"assembly" : null,
				"alleleOrigin" : [
					"germline_variant"
				],
				"heritableTraits" : [
					{
						"trait" : "Tuberous sclerosis syndrome",
						"inheritanceMode" : null
					}
				],
				"genomicFeatures" : [
					{
						"featureType" : "gene",
						"ensemblId" : null,
						"xrefs" : {
							"symbol" : "TSC2"
						}
					}
				],
				"variantClassification" : {
					"clinicalSignificance" : null,
					"drugResponseClassification" : null,
					"traitAssociation" : null,
					"tumorigenesisClassification" : null,
					"functionalEffect" : null
				},
				"impact" : null,
				"confidence" : null,
				"consistencyStatus" : null,
				"ethnicity" : "Z",
				"penetrance" : null,
				"variableExpressivity" : null,
				"description" : null,
				"additionalProperties" : [
					{
						"id" : null,
						"name" : "ClinicalSignificance_in_source_file",
						"value" : "NO_ASSERTION_PROVIDED"
					},
					{
						"id" : null,
						"name" : "ReviewStatus_in_source_file",
						"value" : "NO_ASSERTION_PROVIDED"
					},
					{
						"id" : null,
						"name" : "GenotypeSet",
						"value" : "16:2134585:GTGGCCTCCGGC:-"
					},
					{
						"id" : null,
						"name" : "modeOfInheritance",
						"value" : "[{\"trait\":\"Tuberous sclerosis syndrome\"}]"
					}
				],
				"bibliography" : [ ]
			}

```
