### ISSUE TITLE
REST API: clean up for consistency

### ISSUE THREAD

**Issue by julie-sullivan** [opencb/cellbase#522]
Some of these are for discussion:

 - [ ] #485 - remove the unneeded default paths
 - [ ] deprecate any query you can do via `/search`: `/first`, `/list`, `/count'
 - [ ] Sort direction should be ASC, error if the user provides and invalid value. See https://github.com/opencb/java-common-libs/issues/42
 - [ ] `numberOfTotalResults` - deprecate. Replaced by `numMatches`
 - [ ] `skipCount` - delete. There is already a `count` boolean (defaults to FALSE) so this parameter serves no purpose.
 - [ ] We should pick a case style and use it consistently throughout the API. Now we use a mixture of camelCase and snake_case.

**Comment by julie-sullivan** [comment]
There are several classes that don't seem to be in use:

* Dot server
* Pathway
* Protein interactions
* Phenotype
* MiRNAGene
* MiRNAMature
* Utils

Can we delete? If we need to restore we can revive via git.

**Comment by julie-sullivan** [comment]
```
Caused by: java.lang.NumberFormatException: For input string: "a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.internal.inject.PrimitiveValueOfExtractor.getValue(PrimitiveValueOfExtractor.java:74)
	at org.glassfish.jersey.server.internal.inject.PrimitiveValueOfExtractor.extract(PrimitiveValueOfExtractor.java:91)
	at org.glassfish.jersey.server.internal.inject.QueryParamValueParamProvider$QueryParamValueProvider.apply(QueryParamValueParamProvider.java:78)
	... 72 more
```

**Comment by julie-sullivan** [comment]
Instead of " Please note that this parameter may not be enabled for all web services." only have valid web services for each end point.

This will cause duplication in the code however.

**Comment by julie-sullivan** [comment]
These fields also should only be in certain end points:

* exclude
* include
* sort

**Comment by julie-sullivan** [comment]
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/#!/TFBS/getAllByTfbs

I'm having trouble with the `cellType` parameter. 

* has no description. What should it be? "Type of cell, e.g. K562 or HepG2"
* it doesn't seem to work. The query outcome is the same, regardless of what I put in that field.

**Comment by julie-sullivan** [comment]
```
        queryOptions.put(QueryOptions.SKIP_COUNT, StringUtils.isNotBlank(skipCount) && Boolean.parseBoolean(skipCount));
        queryOptions.put(QueryOptions.COUNT, StringUtils.isNotBlank(count) && Boolean.parseBoolean(count));
```

I removed SKIP_COUNT. However, SKIP_COUNT is what commons is looking for:

```
// MongoDBCollection.java

            if (options != null && options.getInt(QueryOptions.SKIP) <= 0 && options.getInt(QueryOptions.LIMIT) > 0) {
                int numTotalResults;
                if (options.getBoolean(QueryOptions.SKIP_COUNT)) {
                    numTotalResults = -1;
                } else {
                    try {
```

So I will change to set SKIP_COUNT as right now the `count` boolean is having no effect. 

But what did `count` do before? 

Also I'm not sure the logic in the commons is what we are expecting in cellbase.

**Comment by julie-sullivan** [comment]
| param | /info | /search | redundant path queries, e.g. gene/{id}/protein | distinct queries |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| exclude/include/sort  | ✓  | ✓  | ✓  | -  | 
| count  | -  | ✓  | ✓  | -  |
| limit,skip  | -  | ✓  | ✓  | -  |

**Comment by julie-sullivan** [comment]
If I `include` fields and don't explicitly mention `id` I get a null pointer exception:

```
2020-02-10 11:31:03 [qtp1127224355-9] INFO  connection:71 - Opened connection [connectionId{localValue:12, serverValue:2728}] to localhost:27017
java.lang.NullPointerException
	at org.opencb.cellbase.server.rest.feature.IdWSServer.getByFeatureIdInfo(IdWSServer.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

`id` is assumed to be present:

```
            List<CellBaseDataResult<Document>> dbNameList = xRefDBAdaptor.nativeGet(queries, queryOptions);
            for (int i = 0; i < dbNameList.size(); i++) {
                dbNameList.get(i).setId(list.get(i));
                for (Document document : dbNameList.get(i).getResults()) {
                    if (document.get("id").equals(list.get(i))) {
```
Therefore I removed `include` as the user shouldn't be changing this. See 1eddb9213b3d038c854f5afe730c638c68ef95fb

**Comment by julie-sullivan** [comment]
The API `description` parameter is [deprecated](http://docs.swagger.io/swagger-core/v1.5.0/apidocs/io/swagger/annotations/Api.html). 

If you set the description properly using tags, it shows up in swagger like:

![api-description](https://user-images.githubusercontent.com/1663057/74153330-4cca5800-4c08-11ea-8fd5-318f70e27947.png)

I think it makes the API harder to read. 

```
@SwaggerDefinition(tags = {
        @Tag(name = "Species", description = "Species RESTful Web Services API")
}
```
